### ISSUE TITLE
add integration support, found bugs?

### ISSUE THREAD

**Issue by danielnachumdev** [kevinmcguinness/pdf2pptx#1]
It would be of great help if you would add integration support into other projects, as in adding the ability to import functions from you module.
I have tried this workaround:
in `__init__.py` adding `from .cli import main`
and in my code `from pdf2pptx import main as create_pptx`
and using it like this `create_pptx(["INPUT","-o OUTPUT"]`)
which allowed me to use debug features on your code. only to find out that certian attributes and methods names' are defined slightly diffrently (maybe becuase of an update) e.g:
pageCount ->page_count
loadPage ->load_page
getPixmap -> get_pixmap

but I got stuck on `image_data = pixmap.getPNGData()` at line 63
as I didnt seem to find that function or something similar

would appreciate a fix, thanks

**Comment by kevinmcguinness** [comment]
Looks like there have been a bunch of API changes in PyMuPDF since I wrote this. In addition to the changes you mentioned (pageCount -> page_count, etc.) it looks like they changed the Pixmap API significantly, removing the getPNGData function. You should be able to get the same functionality using [pil_tobytes](https://pymupdf.readthedocs.io/en/stable/pixmap.html#Pixmap.pil_tobytes) with format="PNG". I'll look into updating the code for the newer versions of PyMuPDF when I have some time.

**Comment by kevinmcguinness** [comment]
I've updated the code for the new version of the PyMuPDF API. I'll look into making it easier to integrate later

**Comment by kevinmcguinness** [comment]
I updated the code to make integration easier. There is now a function in `__init__.py` called `convert_pdf2pptx` that can be called directly by other programs. You can also use the `quiet=True` option to suppress console output if needed.

**Comment by danielnachumdev** [comment]
thanks for the quick response and fix, thats of great help!
